### ISSUE TITLE
On boot hostapd is started but it fails to advertise the AP.  Works and advertises fine when started manually with netconnectcli start_ap.

### ISSUE THREAD

**Issue by tdicola** [foosel/netconnectd#11]
This is an odd error I'm running into trying to use netconnectd on a Pi 3 and its built in WiFi module.  Hostapd seems to run fine and fire up an AP I can connect to when I run it manually.  I've run through the readme instructions and have netconnectd all setup and running at boot.  However whenever I boot up the Pi with no network cable attached it doesn't seem to be advertising the AP (i.e. laptops and mobile devices can't see the AP I configured).  

If I plug in a network cable and connect to the Pi I can see hostapd and netconnectd are running, for example here's what systemd shows for netconnectd status:
```
pi@raspberrypi:~ $ sudo systemctl status netconnectd.service
● netconnectd.service - LSB: netconnectd daemon
   Loaded: loaded (/etc/init.d/netconnectd)
   Active: active (running) since Mon 2016-03-21 21:03:28 UTC; 13min ago
  Process: 361 ExecStart=/etc/init.d/netconnectd start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/netconnectd.service
           ├─373 /usr/bin/python /usr/local/bin/netconnectd --config /etc/netconnec...
           ├─556 /usr/sbin/hostapd -dd -B /etc/netconnectd.conf.d/hostapd/netconnec...
           └─684 /usr/sbin/dnsmasq --conf-file=/etc/netconnectd.conf.d/dnsmasq/netc...
```

And netconnectcli status shows that it thinks hostapd is running too:
```
pi@raspberrypi:~ $ netconnectcli status
SuccessResponse:
  connections:
    ap:
      True
    wifi:
      False
    wired:
      True
  devs:
    [
      eth0
    ]
  wifi:
    valid_config:
      False
    current_address:
      None
    present:
      True
    current_ssid:
      None
  link:
    True
```

However checking with wifi devices and I fail to see the AP running/being advertised with the name I assigned.  For reference here's my netconnectd config (it's pretty much stock):
```
# control socket to listen on
#socket: /var/run/netconnectd.sock

# wifi and wired interface
interfaces:
  wifi: wlan0
  wired: eth0

# link monitor configuration
#link_monitor:
#  # whether to enable the link monitor
#  enabled: True
#
#  # after how many consecutive link down events to start up the AP
#  max_link_down: 3
#
#  # interval between link checks
#  interval: 10


# access point configuration
ap:
  # nick name under which to save the AP configuration, usually won't need to be chan
  #name: netconnectd_ap

  # driver to use for hostapd, you might have to change this depending
  # on your wifi card/dongle
  driver: nl80211

  # your AP wifi's SSID
  ssid: netconnectdAP

  # your AP wifi's passphrase
  psk: secretkey

  # wifi channel on which the AP should run
  channel: 3

  # ip of the AP on the created wifi, also check if you need to adjust
  # network and range if you change this
  #ip: 10.250.250.1

  # network of the created wifi, also check if you need to adjust ip
  # and range if you change this
  #network: 10.250.250.0/24

  # range of ip addresses to hand out via dhcpd, first ip and last ip,
  # also check if you need to adjust ip and network if you change this
  #range:
  #- 10.250.250.100
  #- 10.250.250.200

  # if you also want to reach your hosts by something like myhost.home,
  # set this, normally unset
  #domain: home

  # whether to create a true AP forwarding to the wired interface, defaults
  # to false
  #forwarding_to_wired: false

# wifi configuration
wifi:
  # nick name under which the wifi connection will be saved, usually
  # no need to change this
  #name: netconnectd_wifi

  # if your system doesn't run NetworkManager, set this to false
  free: false

  # set this to true if you want to reset the wifi interface via rfkill
  # upon interface set up errors during wifi connection, scanning or
  # bringing up the AP, which may happen if the wifi driver hiccups
  #
  # Recommended, but depends on the rfkill command to be available
  kill: true

# various paths of tools used
paths:
  # path to hostapd executable
  #hostapd: /usr/sbin/hostapd

  # folder where to store managed hostapd configuration files
  hostapd_conf: /etc/netconnectd.conf.d/hostapd

  # path to dnsmasq executable
  #dnsmasq: /usr/sbin/dnsmasq

  # folder where to store managed dnsmasq configuration files
  dnsmasq_conf: /etc/netconnectd.conf.d/dnsmasq

  # path to interfaces file to use, usually no need to change this
  #interfaces: /etc/network/interfaces
```

Now here's where things get weird.  If I run `netconnectcli stop_ap` and then `netconnectcli start_ap` the AP fires up and starts advertising perfectly.  I can connect from another machine and get an IP address just fine--everything works great.  For some reason though whenever it runs on boot hostapd runs but doesn't seem to be doing anything.

I've looked at the output of the /var/log/netconnectd.log file and it looks the same for when it boots up vs. explicitly starting with the netconnectcli command.  I'm not sure is there any place to see a log of what hostapd is doing?  Have you run into any similar issues before?  Let me know if there's more info that can help, thanks!
